<?php
/**
 * Product Name: Mage2 All in one
 * Module Name: Mage2_Allinone
 * Created By: Yogesh Shishangiya
 */

$most_viewed_products = $block->mostViewedCollection();
$status               = $block->mostStatus();
$mstViewPrdCount      = count($most_viewed_products);

if ($status) {
    if ($mstViewPrdCount > 0) {
        ?>

        <div class="most-viewed-product">
            <div class="most-viewed-title">
                <h3>
                    <?= /* @noEscape */ $block->mostBlockTitle(); ?>
                </h3>
            </div>
            <div id="most-viewed-products" class="owl-carousel owl-theme most-viewed-products">

                <?php
                foreach ($most_viewed_products as $product) {
                    $product_data = $block->getProductById($product->getId());
                    $product_url  = $product_data->getProductUrl();
                    $imageUrl     = $block->getProductImageUrl($product_data);
                    ?>
                    <div class="most-viewed-item">
                        <a href='<?= /* @noEscape */ $product_url ?>' class='most-viewed-img'>
                            <img src="<?= /* @noEscape */ $imageUrl ?>"
                                 alt="<?= /* @noEscape */ $product_data->getName() ?>"/>
                        </a>
                        <a href='<?= /* @noEscape */ $product_url ?>' class='most-viewed-name'>
                            <?= /* @noEscape */ $product_data->getName() ?>
                        </a>
                        <div class="most-viewed-detail">
                            <div class="most-viewed-price">
                                <?= /* @noEscape */ $block->getProductPrice($product_data); ?>
                            </div>
                            <div class="most-viewed-action">
                                <div class="most-viewed-addtocart">
                                    <?php if ($product_data->getTypeInstance()->hasRequiredOptions($product_data)): ?>
                                        <button class="action tocart primary"
                                                data-mage-init='{"redirectUrl":{"url":"<?= /* @noEscape */
                                                    $block->getAddToCartUrl($product_data) ?>"}}'
                                                type="button" title="<?= /* @noEscape */ __('Add to Cart') ?>">
                                            <span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php
                                        $postData = $block->getAddToCartButtonPostData($product_data);
                                        ?>
                                        <button class="action tocart primary"
                                                data-post='<?= /* @noEscape */ $postData; ?>'
                                                type="button" title="<?= /* @noEscape */ __('Add to Cart') ?>">
                                            <span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>

            </div>
        </div>

        <script>
            require([
                'jquery',
                'feature'
            ], function () {
                'use strict';
                jQuery("#most-viewed-products").owlCarousel({
                    autoPlay: 3000, //3000 Set AutoPlay to 3 seconds
                    margin: 10,
                    items: 4,
                    itemsDesktop: [1199, 4],
                    itemsDesktopSmall: [979, 3],
                    itemsTablet: [768, 2],
                    itemsMobile: [479, 1],
                    navigation: true,
                    pagination: false
                });
            });
        </script>

        <?php
    }
}
?>
